### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by 7x5** [EmilSpj/Space-Invaders#1]
game sometimes crashes when you lose

**Comment by EmilSpj** [comment]
Hello, I haven't noticed this, but I will look into it and keep you updated :)

**Comment by EmilSpj** [comment]
I have looked into it and played several games, and I was wondering what Python Version and PyGame version you were using so I could test with yours. I haven't noticed the bug you are referencing.

**Comment by 7x5** [comment]
it seems to be fixed now
